### ISSUE TITLE
[ Bug ] Add v24.1. conditional logic to tower.yml.tpl

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#130]
As per this [(internal) development ticket](https://github.com/seqeralabs/platform/pull/6584), the upgrade to Micronaut 4 has changed some system configuration values we expose via the [_tower.yml_ file](https://github.com/seqeralabs/cx-field-tools-installer/blob/master/assets/src/tower_config/tower.yml.tpl). 

## Changes
| Previous                        | New                                               |
| --------------------------------- | --------------------------------------------------- |
| `micronaut.security.token.jwt.generator.access-token.expiration`             | `micronaut.security.token.generator.access-token.expiration`                             |

## Affects
Bug affects the [1.3.0 and 1.3.1 Releases](https://github.com/seqeralabs/cx-field-tools-installer/releases).

**Comment by gwright99** [comment]
Testing with `v24.2.2`:
```yaml
micronaut:
  application:
    name: tower-dev

  http:
    client:
      read-timeout: 30s

  security:
    redirect:
      login-success : "/auth?success=true"
      login-failure : "/auth?success=false"

    # WARNING! Do not disable `refresh-token.enabled`. User and pipeline authentication affected equally - breaks long pipelines. (Last updated: March 2/24)
    token:

        # Tower embeds an access-refresh tokens pair in the head job when launching a pipeline.
        # Access token used by Nextflow to authenticate with Tower. 
        # Defaults: Access Token: 1 hour  | Refresh Token:  6 hours
        #
        # Refresh-token expiry may require bumping if your job takes too long to be scheduled (i.e. 6h+).
        # Ensure the `tower.ephemeral.duration` value exceeds the lifespan of your refresh token expiration as well.
      generator:
        access-token:
          expiration: 3600                                # Duration in seconds (ANOMALY: Integer only!) dont add time unit at end!
        refresh-token:
          enabled: true                                   # true | false
          expiration: 6h                                  # Duration is integer + unit (e.g. 6h | 1d)
```

With `23.4.5`:
```yaml
micronaut:
  application:
    name: tower-dev

  http:
    client:
      read-timeout: 30s

  security:
    redirect:
      login-success : "/auth?success=true"
      login-failure : "/auth?success=false"

    # WARNING! Do not disable `refresh-token.enabled`. User and pipeline authentication affected equally - breaks long pipelines. (Last updated: March 2/24)
    token:

      jwt:
        # Tower embeds an access-refresh tokens pair in the head job when launching a pipeline.
        # Access token used by Nextflow to authenticate with Tower. 
        # Defaults: Access Token: 1 hour  | Refresh Token:  6 hours
        #
        # Refresh-token expiry may require bumping if your job takes too long to be scheduled (i.e. 6h+).
        # Ensure the `tower.ephemeral.duration` value exceeds the lifespan of your refresh token expiration as well.
        generator:
          access-token:
            expiration: 3600                                # Duration in seconds (ANOMALY: Integer only!) dont add time unit at end!
          refresh-token:
            enabled: true                                   # true | false
            expiration: 6h                                  # Duration is integer + unit (e.g. 6h | 1d)
```
