### ISSUE TITLE
Add ephemeral endpoint configuration to tower.yml.tpl

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#14]
Fine-grained control over how long the Tower ephemeral API endpoint remains available (default `8h`).

```yaml
# Option examples: 8h, 12h, 2d
tower:
  ephemeral:
    duration: 8h
```

Useful in cases where there is a multi-hour/day delay between when the workflow was submitted to the scheduler and when it actually starts running (and makes a callback to Tower via this endpoint).
