### ISSUE TITLE
[ Enhancement ] -- Consider extending cloud-prices & audit-log config

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#159]
Source: [https://github.com/seqeralabs/support-backlog/issues/114](https://github.com/seqeralabs/support-backlog/issues/114)

```yaml
  cron:
    cloud-prices:
      clean-up:
        enabled: false
        chunk-size: 1000
        time-offset: 30d
        short-delay: 10s
        long-delay: 5m
    audit-log:
      clean-up:
        enabled: true
        chunk-size: 1000
        time-offset: 365d
        short-delay: 10s
        long-delay: 5m
```

Audit log `time-offset` is already configurable.  Could be worthwhile to expose other values too, but care is required re: chunk size and delay values to ensure values that differ from the default do not break system behaviour.
