### ISSUE TITLE
Add `tower.yml.tpl` entries for member and collaborator management

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#16]
An individual must have an account in the Tower instance before they can be added to Org/Workspace. Tower offers a convenience setting where it will automatically create the desired account if one adds an email that is not yet affiliated with a Tower account. 

Depending on the level of control a Tower Enterprise administrator wants to enforce one or both of these automatic-creation settings may need to be modified.

```yaml
# tower.ym
tower:
  member:
    auto-create-user: true             # Default: true
  participant:                                # aka "Collaborator"
    auto-create-user: false            # Default: false
```
