### ISSUE TITLE
[ Enhancement ] Consider allowing users accounts to be auto-provisioned

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#162]
This configuration snippet allows accounts to be auto-provisioned if an individual is added to a Workspace but does not yet exist in the Seqera Platform instance:

```yaml
tower:
  participant:
    auto-create-user: true
  eval:
    teamId: xxxxx
    workspaces: xxxxx
```

There may be some [nuances between Collaborators and Member behaviour](https://github.com/seqeralabs/tower-backlog/issues/898#issuecomment-1415134230). 

TO DO: Discuss with Product / Eng before adding to project.
