### ISSUE TITLE
[ Enhancement ] Add workflow cleanup config

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#196]
Only valid in (?)25.1(?) and beyond.

```
# tower.env
TOWER_WORKFLOW_CLEANUP_ENABLED = true

# tower.yml
tower:
  workflow-cleanup:
    enabled: ${TOWER_WORKFLOW_CLEANUP_ENABLED:false}
```

PR reference: https://github.com/seqeralabs/platform/pull/7639
