### ISSUE TITLE
Add `tower.yml` entry to better control job statuses

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/cx-field-tools-installer#69]
As per [https://support.seqera.io/helpdesk/tickets/5093](https://support.seqera.io/helpdesk/tickets/5093), the Seqera Platform (Enterprise) exposes configuration values to control how job statuses are displayed in the Runs screen.

## Config Snippet
```yaml
# Sources (Seqera Platform ): 
#  - WorkflowWatchdogJob.groovy
#  - ReconcileProgressJob.groovy

# tower.yml
tower:
  cron:
    watchdog:
      delay: 5s
      interval: 1m
      expire: 190s
      zombie: 1d
    progress-stats:
      delay: 10s
      interval: 1m
      enabled: true
```

## To Do:

1. [ ] Clarify behaviour based on information @swampie shared with client June 10/24 **prior** to addition into project.
2. [ ] Once clarification occurs:
    1. [ ] Add snippet in tower.yml.tpl
